# Generated by Django 4.0 on 2021-12-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moeda", "0002_alter_moeda_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moeda",
            name="country_coin",
        ),
        migrations.AddField(
            model_name="moeda",
            name="name_coin",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Nome da moeda"
            ),
        ),
    ]
