# Generated by Django 4.0 on 2021-12-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moeda", "0003_remove_moeda_country_coin_moeda_name_coin"),
    ]

    operations = [
        migrations.AddField(
            model_name="moeda",
            name="continent",
            field=models.CharField(max_length=30, null=True, verbose_name="Continente"),
        ),
    ]
