# Generated by Django 4.0 on 2021-12-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moeda", "0004_moeda_continent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moeda",
            name="continent",
        ),
        migrations.RemoveField(
            model_name="moeda",
            name="name_coin",
        ),
        migrations.AddField(
            model_name="moeda",
            name="initials",
            field=models.CharField(
                choices=[("BRL", "Real"), ("JPY", "Iene"), ("EUR", "Euro")],
                max_length=3,
                null=True,
                verbose_name="Sigla da moeda",
            ),
        ),
    ]
