name: Django CI

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
      SECRET_KEY: ''
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Copying configurations
      run: |
        cp contrib/env-sample .env
    - name: Install Dependencies
      run: |
        pip install pipenv
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        pipenv run flake8 .
    - name: Rodar Testes Automáticos
      env: 
        SECRET_KEY: 'your-genereated-secret_key'
        ENVIROMENT: 'production'
      run: |
          pytest cotacao_api --cov=cotacao_api
    - name: Relatório Coverage
      env:
          CODECOV_TOKEN: "a25e3e4c-71da-4e0c-9dd2-db308c481bb4"
      run: |
          codecov        
        
